import spotipy
import os
import requests
from spotipy.oauth2 import SpotifyOAuth
from dotenv import load_dotenv

load_dotenv()

client_id = os.getenv("SPOTIFY_CLIENT_ID")
client_secret = os.getenv("SPOTIFY_CLIENT_SECRET")
redirect_uri = os.getenv("SPOTIFY_REDIRECT_URI")

scope = "playlist-read-collaborative,playlist-modify-public"
sp = spotipy.Spotify(
    auth_manager=SpotifyOAuth(
        client_id=client_id,
        client_secret=client_secret,
        redirect_uri=redirect_uri,
        scope=scope
    )
)

playlist = sp.playlist(playlist_id="5hfkBedabkUiLAJdHBgIAa")
playlist_info = playlist['tracks']

songs_audio_features = []
all_song_ids = []

while playlist_info:
    song_ids = []
    songs = playlist_info['items']

    for track in songs:
        song_ids.append(track['track']['id'])
        all_song_ids.append(track['track']['id'])
    
    afs = sp.audio_features(tracks=song_ids)
    for idx, af in enumerate(afs):
        af['song_name'] = songs[idx]['track']['name']
        af['artist'] = songs[idx]['track']['artists'][0]['name']
        songs_audio_features.append(af)
    
    if playlist_info['next']:
        playlist_info = sp.next(playlist_info)
    else:
        break

bops_ids = []
softs_ids = []

# Sorting algorithm goes here


sp.user_playlist_create(
    user='yitzerflogan',
    name='autogenerated',
    public=True,
    collaborative=False,
    description="created by spotipy"
)